### ISSUE TITLE
Crash when block synchronisation started

### ISSUE THREAD

**Issue by felivix** [etclabscore/multi-geth#455]
Hi

Just installed CoreGeth version: 1.12.7-unstable on a Raspberry Pi4 8Gb with Ubuntu 21.10.

Unfortunately the block synchronization stopped midway and the following error appears continuously.
Is there a way to fix it? I did "geth removedb" but the problem persists.

```
INFO [02-11|16:38:21.103] Block synchronisation started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xb70014]

goroutine 1115 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestorBinarySearch(0x4000f5e000, 0x400dd03110, 0x1, 0xd87587, 0x7cde89)
        /home/ubuntu/core-geth/eth/downloader/downloader.go:980 +0x8f4
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0x4000f5e000, 0x400dd03110, 0x408241f200)
        /home/ubuntu/core-geth/eth/downloader/downloader.go:826 +0x3cc
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0x4000f5e000, 0x400dd03110, {0xba, 0x8c, 0xb8, 0x92, 0x29, 0xa6, 0x2f, 0x86, ...}, ...)
        /home/ubuntu/core-geth/eth/downloader/downloader.go:479 +0x4dc
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0x4000f5e000, {0x400e15a280, 0x40}, {0xba, 0x8c, 0xb8, 0x92, 0x29, 0xa6, 0x2f, ...}, ...)
        /home/ubuntu/core-geth/eth/downloader/downloader.go:431 +0x4a8
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0x4000f5e000, {0x400e15a280, 0x40}, {0xba, 0x8c, 0xb8, 0x92, 0x29, 0xa6, 0x2f, ...}, ...)
        /home/ubuntu/core-geth/eth/downloader/downloader.go:326 +0x6c
github.com/ethereum/go-ethereum/eth.(*handler).doSync(0x40013aa400, 0x4084b18540)
        /home/ubuntu/core-geth/eth/sync.go:289 +0x220
github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync.func1(0x4000c32ba0, 0x4084b18540)
        /home/ubuntu/core-geth/eth/sync.go:265 +0x34
created by github.com/ethereum/go-ethereum/eth.(*chainSyncer).startSync
        /home/ubuntu/core-geth/eth/sync.go:265 +0x84
```

**Comment by felivix** [comment]
I deleted the chaindata, did "geth removedb", and restarted a fresh resync. For hours it run smoothly and then crashed again. 
Now when I try to resync with sudo geth --syncmode fast --cache 1024 --datadir /mnt/ssd/ether 
I get the error: Fatal: Failed to register the Ethereum service: genesis not found in chain

Is there a way to fix the genesis not found issue?

**Comment by meowsbits** [comment]
Hey there @felivix. Thanks for reporting this. As you'll see, I've got a PR in addressing this now.
